# Generated by Django 5.0.1 on 2024-01-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=56, verbose_name='Title')),
                ('description', models.CharField(default=None, max_length=512, verbose_name='Description')),
                ('author', models.CharField(default='Anonymous', max_length=56, verbose_name="Author's name")),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=56, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
