# Generated by Django 5.0.1 on 2024-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Noimage', max_length=56, upload_to='', verbose_name='Image'),
        ),
    ]
